"""Terminal and JSON output."""

from __future__ import annotations

import json
import sys
from typing import Any, Dict, List

from .audit import CRITICAL, NOTICE, SOURCE_BODY, SOURCE_PLUGIN, WARNING, AuditResult

BOLD, DIM, RESET = "\033[1m", "\033[2m", "\033[0m"
RED, YELLOW, BLUE, GREEN = "\033[31m", "\033[33m", "\033[34m", "\033[32m"
SEVERITY_STYLE = {CRITICAL: RED, WARNING: YELLOW, NOTICE: BLUE}


def use_color(flag_no_color: bool) -> bool:
    return not flag_no_color and sys.stdout.isatty()


class Painter:
    def __init__(self, enabled: bool) -> None:
        self.enabled = enabled

    def __call__(self, code: str, text: str) -> str:
        return f"{code}{text}{RESET}" if self.enabled else text


def print_audit(result: AuditResult, site: str, color: bool = True, limit: int = 40,
                out=None) -> None:
    out = out or sys.stdout
    c = Painter(color)
    p = lambda s="": print(s, file=out)

    p(f"\n{c(BOLD, 'Audit - ' + site)}")
    p(c(DIM, "-" * 64))
    p(f"  Items scanned        {result.pages_scanned}")
    p(f"  Live pages fetched   {result.pages_fetched}")
    p(f"  Pages with JSON-LD   {result.pages_with_jsonld}")
    if result.plugins_seen:
        owners = ", ".join(f"{k} ({v} blocks)" for k, v in sorted(result.plugins_seen.items()))
        p(f"  Schema generated by  {owners}")
    if result.pages_unreachable:
        p(f"  Unreachable          {len(result.pages_unreachable)} "
          + c(DIM, "(published but the front end did not answer 200)"))
    p(f"  Findings             {len(result.findings)}")

    for severity in (CRITICAL, WARNING, NOTICE):
        group = result.by_severity(severity)
        if not group:
            continue
        style = SEVERITY_STYLE[severity]
        p(f"\n{c(style + BOLD, severity.upper())} {c(DIM, f'({len(group)})')}")
        shown = group if limit <= 0 else group[:limit]
        for f in shown:
            tag = ""
            if f.source == SOURCE_PLUGIN:
                tag = c(DIM, f" [{f.plugin}]")
            elif f.source == SOURCE_BODY:
                tag = c(GREEN, " [repairable]")
            elif f.rule != "stale-draft":
                tag = c(DIM, f" [{f.source}]")
            p(f"  {c(style, '*')} {f.message}{tag}")
            p(f"    {c(DIM, (f.page_title or '')[:60] + ' - ' + f.page_url)}")
            if f.detail:
                p(f"    {c(DIM, f.detail[:220])}")
        if limit > 0 and len(group) > limit:
            p(f"  {c(DIM, f'... {len(group) - limit} more; use --limit 0 or --json to see all')}")

    fixable = result.auto_fixable
    hand = result.hand_edits
    p()
    p(f"{c(GREEN, str(len(fixable)))} finding(s) can be staged as WordPress drafts by this tool.")
    if hand:
        p(f"{len(hand)} finding(s) live in schema this tool must not write; "
          f"see 'cleanuprtx hand-edits' for exact locations.")
    if result.pages_unreachable:
        p(c(DIM, "Unreachable pages were not audited; check 'cleanuprtx forbidden'."))


def print_hand_edits(result: AuditResult, color: bool, out=None) -> None:
    out = out or sys.stdout
    c = Painter(color)
    p = lambda s="": print(s, file=out)
    groups: Dict[str, List[Any]] = {}
    for f in result.hand_edits:
        groups.setdefault(f.hand_edit or "(unknown location)", []).append(f)
    if not groups:
        p("Nothing needs a hand edit.")
        return
    for where, items in groups.items():
        p(f"\n{c(BOLD, where)}")
        for f in items:
            p(f"  * {f.message} - {c(DIM, f.page_url)}")
            if f.detail:
                p(f"    {c(DIM, f.detail[:200])}")
            if f.patch:
                p(f"    suggested value: {c(DIM, json.dumps(f.patch.get('value', f.patch)))}")


def print_repairs(repairs: List[Any], color: bool = True, out=None) -> None:
    out = out or sys.stdout
    c = Painter(color)
    p = lambda s="": print(s, file=out)
    if not repairs:
        p(c(DIM, "No repairs in this state."))
        return
    for r in repairs:
        state = f" {c(DIM, '(' + r.state + ')')}" if r.state not in ("pending", "approved") else ""
        p(f"  {c(BOLD, r.repair_id)}  {r.message}{state}")
        p(f"    {c(DIM, (r.page_title or '')[:60])}  {c(DIM, r.kind + '/' + str(r.page_id))}")
        p(f"    {c(DIM, r.page_url)}")
        node = r.target.get("node_id") or "/".join(map(str, r.target.get("path", [])))
        p(f"    node {c(DIM, node or '?')}  ({'/'.join(r.target.get('node_types', [])) or '?'})")
        if r.patch.get("op") == "rename_id":
            p(f"    rename @id {c(DIM, r.patch['old'])} -> {c(DIM, r.patch['new'])}")
        else:
            p(f"    set {r.patch.get('key')} = {c(DIM, json.dumps(r.patch.get('value')))}")
        if r.result and r.state in ("failed", "stale"):
            p(f"    {c(RED, r.result[:200])}")


def write_json(result: AuditResult, path: str) -> None:
    payload = {
        "pages_scanned": result.pages_scanned,
        "pages_fetched": result.pages_fetched,
        "pages_with_jsonld": result.pages_with_jsonld,
        "pages_unreachable": result.pages_unreachable,
        "plugins_seen": result.plugins_seen,
        "findings": [f.to_dict() for f in result.findings],
    }
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
